### ISSUE TITLE
With WSL

### ISSUE THREAD

**Issue by mlozier** [sickcodes/osx-serial-generator#10]
WSL supports GUI apps natively now.  What would need to be done to make this work on WSL?  I ran the OpenCore-Boot.sh script, but it failed to run with "Could not initialize SDL(No available video device) - exiting."  libsdl is installed on my instance of Ubuntu on WSL2.

**Comment by sickcodes** [comment]
https://github.com/sickcodes/Docker-OSX#id-like-to-run-docker-osx-with-wsl2-windows-ubuntu

Allegedly this is working perfectly on WSL2 now: https://github.com/sickcodes/Docker-OSX/issues/131#issuecomment-885924090

**Comment by sickcodes** [comment]
Working WSL2/WSLg

In windows 10 you need to ensure KVM is enabled and x11-apps is installed. 

In Windows 11 just need WSLg apparently 


Follow the steps here: https://github.com/sickcodes/Docker-OSX#id-like-to-run-docker-osx-with-wsl2-windows-ubuntu ☺️
